version: 0.2
#This declares the buildspec version AWS CodeBuild understands. 0.2 is the current standard
#for multi-phase builds (install, pre_build, build, post_build).
env:
  variables:
  # Environment variables for AWS CodeBuild
    AWS_ACCOUNT_ID: "266826707547" 
    ECR_REPO_NAME: "springboot-app"
    AWS_REGION: "us-east-1"
 
phases:
  install:
    runtime-versions:
      # runtime-versions: Prepares Java 17ß
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - echo "Compiling Spring Boot app with Maven..."
      - mvn clean package -DskipTests
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "Generating imagedefinitions.json for ECS..."
      - printf '[{"name":"springboot-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
